language: node_js
node_js: stable
cache:
  bundler: true
  directories:
  - node_modules
script:
- npm run release
deploy:
  provider: npm
  email: supermanchc@gmail.com
  api_key:
    secure: mBlNOBaY+RKzlIVN8WZLDDRaEBELjzIHjsk4eJUFHQCOunykEqXI+oihiXweuRnG7e+RH9JqqfqXxig+5xsYeEortpPFSvegk5gXX2S1z39Zuv+kPwI5SQi7CTQy2mAUXKE3/8SMZPJHZL7virRdZ5vY6S8fceHJZynJrPYeGZ1SgIR6EozNkyDRjSfdKU0UveyvDaHcS0ti5YnkhfTu71RMGtUAXtiH5gg29mfOupZobNHOQ1Ypm8ICmeN/d5yzacWhNafJIjW1WrZ5LGVmttV6VG+BvJbwU0UW9Y5sUCjFvKjvnk8/Nqp6kYGrhXyvh1OZiNHXK7rqEbd7TweTMuMFSYxa7ypcyt1aOAQgTs5XXk5AVp0j2blOcSiMht3cNCW6iRQMKVtykVAxG5yZej5hD9xKIHx7MQUN4q3yBF6cZw2je0Nz6txF6N+cYx5uizcF5NMVgSoOoeE8YHqD5aYjo7ljQBrfXpfFi+6aiy0onbfpq1kVHvAVQCWaKiw1dTBQLf1OnTQ33yT4FktZ84XrV1KbzGA9R3aCcnjYLQQ4ItywyNlGLgCfXYZ5W0XE3HVLOpqZyumDXIPPSrS3cgQoftjyl9WzK2mdfO/G9gExI3IczywI0FlxDZAlG6dDRnl/qk4AF7/GST+hakc5XrQ3mnWaj/AkdUCzuDDFqcw=
  on:
    branch: master
    skip_cleanup: true
