
language: node_js
node_js:
  - "node"
script:
- npm run build
deploy:
  - provider: npm
    email: supermanchc@gmail.com
    api_key: $NPM_KEY
    skip-cleanup: true
    on:
      branch: master
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist
    on:
      branch: master
    
