
language: node_js
node_js:
  - "node"

script:
  - npm run pages
jobs:
  include:
    - stage: ghpages
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: dist
        on:
          branch: master
    - stage: deploy
      script: npm run build
      deploy:
        provider: npm
        email: supermanchc@gmail.com
        api_key: $NPM_KEY
        skip-cleanup: true
        on:
          tags: true

# You can specify the order for stages
stages:
  - name: deploy
    if: tag IS present # conditional build, only deploy when tag is present